# Generated by Django 3.2.5 on 2021-08-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_faculty'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendations', to='college.faculty'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
