# Generated by Django 3.2.5 on 2021-07-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subject_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='timetables',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='api.Day'),
        ),
    ]
