# Generated by Django 3.2.5 on 2021-08-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210808_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gtimetable',
        ),
    ]
