# Generated by Django 3.2.5 on 2021-08-10 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_gtimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='material',
            name='college',
        ),
        migrations.RemoveField(
            model_name='material',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_by_contributor',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_by_faculty',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
