# Generated by Django 3.2.5 on 2021-08-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210810_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Textbook',
        ),
    ]
