# Generated by Django 3.2.5 on 2021-07-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
