# Generated by Django 3.2.5 on 2021-07-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210711_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_code', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=30)),
                ('college_image', models.URLField(blank=True)),
                ('link_image', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
            ],
        ),
    ]
