# Generated by Django 3.2.5 on 2021-07-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210717_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='api.college')),
            ],
            options={
                'unique_together': {('course_code', 'college')},
            },
        ),
    ]
