# Generated by Django 3.2.5 on 2021-07-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='api.college')),
            ],
            options={
                'unique_together': {('branch_code', 'college')},
            },
        ),
    ]
