# Generated by Django 3.2.5 on 2021-07-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'college', 'branch')},
        ),
    ]
