# Generated by Django 3.2.5 on 2021-07-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_subject_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject_code', 'college', 'branch')},
        ),
    ]
