# Generated by Django 3.2.5 on 2021-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_delete_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='portion_link',
            field=models.CharField(default='', max_length=35),
        ),
    ]
