# Generated by Django 3.2.5 on 2021-07-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_gsheettable_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsheettable',
            name='gsheet_src',
            field=models.URLField(max_length=90),
        ),
        migrations.AlterUniqueTogether(
            name='gsheettable',
            unique_together={('college', 'branch', 'year')},
        ),
    ]
