# Generated by Django 3.2.5 on 2021-07-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210719_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gsheettable',
            new_name='Gtimetable',
        ),
    ]
