# Generated by Django 3.2.5 on 2021-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_gsheettable_gtimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='description',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='posted_by',
        ),
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='link',
            field=models.URLField(max_length=35),
        ),
    ]
