# Generated by Django 3.2.5 on 2021-07-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210723_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_by',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_by_contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendations', to='api.contributor'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_by_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendations', to='api.faculty'),
        ),
    ]
