# Generated by Django 3.2.5 on 2021-08-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210723_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
