# Generated by Django 3.2.5 on 2021-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='colleges',
            field=models.ManyToManyField(related_name='years', to='college.College'),
        ),
    ]
