# Generated by Django 3.2.5 on 2021-08-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='college',
            new_name='colleges',
        ),
    ]
