# Generated by Django 3.2.5 on 2021-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_rename_college_branch_colleges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='branch',
            new_name='branchs',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='college',
            new_name='colleges',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='year',
            new_name='years',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='portion_link',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD'), ('FOURTH', 'FOURTH')], default='FIRST', max_length=8, unique=True),
        ),
    ]
