# Generated by Django 3.2.5 on 2021-08-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20210807_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='branchs',
            new_name='branches',
        ),
    ]
