# Generated by Django 3.2.5 on 2021-08-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_rename_branchs_subject_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portion',
            old_name='branch',
            new_name='branches',
        ),
        migrations.RenameField(
            model_name='portion',
            old_name='college',
            new_name='colleges',
        ),
        migrations.RenameField(
            model_name='portion',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.RenameField(
            model_name='portion',
            old_name='year',
            new_name='years',
        ),
    ]
