# Generated by Django 3.2.5 on 2021-08-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gtimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsheet_src', models.URLField(max_length=90)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gsheettables', to='college.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gsheettables', to='college.college')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gsheettables', to='college.year')),
            ],
        ),
    ]
