@hostname = http://localhost:8000

### get request to get the authorisation url
GET {{hostname}}/auth/o/facebook/ 
?redirect_uri={{hostname}}/facebook

### facbook login

@state = bC12oaJRx404iVhosxkZ1pcwnjxfArOM
@code = 4%2F0AX4XfWh_urPbSxoHEspl1tRTYa2KFgVoUJNwYqfXMHlI4KRo4vHqkD3F7y4UB2b2sQu-VA

POST {{hostname}}/auth/o/google-oauth2/
?state={{state}}
&code={{code}}
Content-Type: application/x-www-form-urlencoded
