# @hostname = http://localhost:8000
@hostname = https://edtech-dj.herokuapp.com


### get request to get the authorisation url
GET {{hostname}}/auth/o/google-oauth2/ 
?redirect_uri={{hostname}}


### google login

@state = bC12oaJRx404iVhosxkZ1pcwnjxfArOM
@code = 4%2F0AX4XfWjocXOfNq04-tyuj0FTGdcWcBKEJqTtanjcbYfGNMhRh3NJdgbt5Fsg4qYA349hyg

# @name login
POST {{hostname}}/auth/o/google-oauth2/
?state={{state}}
&code={{code}}
Content-Type: application/x-www-form-urlencoded


### get the current user
@access_token_for_get_request = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMwMjYwMzg0LCJqdGkiOiJlNzU2YTg4M2MyYWU0NDkxOWE0ZTliNTM3NmY2YzhkYSIsInVzZXJfaWQiOjF9.7w_1PPh5OhmlDJDDMF05ElmSUZC8LRLDWX88Ci76GpQ
GET {{hostname}}/auth/users/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}

### user profile update
### get user profile
GET {{hostname}}/auth/profile/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}


### updateing user profile data
PUT {{hostname}}/auth/profile/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMwMjYwMzg0LCJqdGkiOiJlNzU2YTg4M2MyYWU0NDkxOWE0ZTliNTM3NmY2YzhkYSIsInVzZXJfaWQiOjF9.7w_1PPh5OhmlDJDDMF05ElmSUZC8LRLDWX88Ci76GpQ

{
  "id": 23,
  "user_email": "rajnaikdhulapkar@gmail.com",
  "user": 23,
  "college": "NITG",
  "branch": 2,
  "year": 1
}


