@hostname = http://localhost:8000
# @hostname = https://edtech-dj.herokuapp.com


### get request to get the authorisation url
GET {{hostname}}/auth/o/google-oauth2/ 
?redirect_uri={{hostname}}


### google login

@state = bC12oaJRx404iVhosxkZ1pcwnjxfArOM
@code = 4%2F0AX4XfWgKxZDBeQ7Ba77VD3GHWox0wihYww1tXKm8sK0WLX6DQkZJg7MjXR7yesRrsrAr1w

# @name login
POST {{hostname}}/auth/o/google-oauth2/
?state={{state}}
&code={{code}}
Content-Type: application/x-www-form-urlencoded


### get the current user
@access_token_for_get_request = {{login.response.body.$.access}}
GET {{hostname}}/auth/users/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}

