@hostname = http://localhost:8000
@user_email = dhulapkarraj@gmail.com
@user_password = BasicUserPassword
@user_password_reseted = BasicUserPasswordReseted
@user_first_name = Raj
@user_last_name = Dhulapkar


### crete a user
POST {{hostname}}/auth/users/ HTTP/1.1
Content-Type: application/json

{
    "email": "{{user_email}}",
    "first_name": "{{user_first_name}}",
    "last_name": "{{user_last_name}}",
    "password": "{{user_password}}",
    "re_password": "{{user_password}}" 
}

  
### user acivation/ user accoutn verification
# http://localhost:8000/activate/Mg/aru65z-a1295f51e2707300bbf199a60fd66447
@uid = Mg  
# these uid and token are obtained from email sent to the user
@token = aru65z-a1295f51e2707300bbf199a60fd66447
POST {{hostname}}/auth/users/activation/ HTTP/1.1
Content-Type: application/json

{
    "uid": "{{uid}}",
    "token": "{{token}}"
}


### user login / getting refresh and access token
# @name login
POST {{hostname}}/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "{{user_email}}",
    "password": "{{user_password}}"
}


### get a new accres token with the refresh token
@refresh_token = {{login.response.body.$.refresh}}
POST {{hostname}}/auth/jwt/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "{{refresh_token}}"
}

### Reset Password to get confirmaion email
POST {{hostname}}/auth/users/reset_password/ HTTP/1.1
Content-Type: application/json

{
    "email": "{{user_email}}"
}


### Reset Password Confirmation
# http://localhost:8000/password/reset/confirm/MQ/arr2oo-59a2a4b6b6b50c53c9162649cf245afa
@uid_pass_reset = MQ
@token_pass_reset = arr2oo-59a2a4b6b6b50c53c9162649cf245afa

POST {{hostname}}/auth/users/reset_password_confirm/ HTTP/1.1
Content-Type: application/json

{
    "uid": "{{uid_pass_reset}}",
    "token": "{{token_pass_reset}}",
    "new_password": "{{user_password_reseted}}",
    "re_new_password": "{{user_password_reseted}}"
}


### user login after password reset / getting refresh and access token
# @name login_after_pass_reset
POST {{hostname}}/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "{{user_email}}",
    "password": "{{user_password_reseted}}"
}


### to verify is authenticated
@access_token_for_verification = {{login_after_pass_reset.response.body.$.access}}
# @access_token_for_verification = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NTQ4NTQ5LCJqdGkiOiJjM2E4ZmJiZjk4ZDA0NzYzYjE2M2JhMTcyZWQ0ZTZmZSIsInVzZXJfaWQiOjF9.N3k3Tkczwe86rZXrCtpnE5gmFCC9zHYAiaSGe5lSQ5A
POST {{hostname}}/auth/jwt/verify/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "token": "{{access_token_for_verification}}"
}

### get api view
@access_token_for_get_request = {{login.response.body.$.access}}
GET {{hostname}}/api/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}


### get current user
GET {{hostname}}/auth/users/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}

# ### update user info
# PUT  {{hostname}}/auth/users/me/ HTTP/1.1
# Content-Type: application/json
# Authorization: JWT {{access_token_for_get_request}}

# {
#     "last_name": "Dhulapkar"
# }