@hostname = http://localhost:8000
# @hostname = https://edtech-dj.herokuapp.com
@user_email = dhulapkarraj@gmail.com
@user_password = BasicUserPassword

### user login / getting refresh and access token
# @name login
POST {{hostname}}/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email": "{{user_email}}",
    "password": "{{user_password}}"
}


### get list of subjects
@access_token_for_get_request = {{login.response.body.$.access}}


GET {{hostname}}/api/subject/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}


### get list of portions

GET {{hostname}}/api/portion/
?page=1
&page_size=5 HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}


### get list of faculty

GET {{hostname}}/api/faculty/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}

### get list of gtimetable

GET {{hostname}}/api/gtimetable/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}


### user profile update
### get user profile
GET {{hostname}}/auth/profile/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}


### updateing user profile data
PUT {{hostname}}/auth/profile/me/ HTTP/1.1
Content-Type: application/json
Authorization: JWT {{access_token_for_get_request}}

{
  "id": 13,
  "user_email": "dhulapkarraj@gmail.com",
  "user": 8,
  "college": "NITG",
  "branch": 1,
  "year": 1
}