# Generated by Django 3.2.5 on 2021-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_gtimetable'),
        ('content', '0002_contributor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=250)),
                ('is_affiliate_link', models.BooleanField(default=False)),
                ('cover_image', models.URLField()),
                ('branches', models.ManyToManyField(blank=True, null=True, related_name='textbooks', to='college.Branch')),
                ('colleges', models.ManyToManyField(blank=True, null=True, related_name='textbooks', to='college.College')),
                ('subjects', models.ManyToManyField(related_name='textbooks', to='college.Subject')),
                ('years', models.ManyToManyField(related_name='textbooks', to='college.Year')),
            ],
        ),
    ]
