# Generated by Django 3.2.5 on 2021-08-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_gtimetable'),
        ('content', '0004_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.URLField()),
                ('recommended_by_contributor', models.ManyToManyField(blank=True, null=True, related_name='recommendations', to='content.Contributor')),
                ('recommended_by_faculty', models.ManyToManyField(blank=True, null=True, related_name='recommendations', to='college.Faculty')),
            ],
        ),
    ]
