# Generated by Django 3.2.5 on 2021-08-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_by_contributor',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_by_faculty',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
