# Generated by Django 3.2.5 on 2021-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_gtimetable'),
        ('content', '0006_auto_20210817_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='textbooks', to='college.Branch'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='colleges',
            field=models.ManyToManyField(blank=True, related_name='textbooks', to='college.College'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='textbooks', to='college.Subject'),
        ),
    ]
