# Generated by Django 3.2.5 on 2021-08-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210817_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Textbook',
        ),
    ]
